services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  data: